# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  paths:
    include:
    - server_web_app/*
    exclude:
    - azure_infra/*
    - client_web_app/*
  branches:
    include:
    - master

variables:
  path: 'server_web_app'
  zipPath: 'server_web_app/'

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: 'Build Artifact'
    jobs:
    - job: 'init'
      displayName: 'Initialize Project'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      
      - script: |
          cd $(path)
          npm install
          cd ..
        displayName: 'npm install'
      
      - script: |
          cd $(path)
          npm run test
        displayName: 'npm run test'

    - job: 'build'
      displayName: 'Build Artifact'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(zipPath)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop_server_dev'
          publishLocation: 'pipeline'

  - stage: deploy
    displayName: 'Deploy to Dev'
    jobs:
    - job: 'deploy'
      displayName: 'Deploy to Dev'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop_server_dev'
          targetPath: '$(Pipeline.Workspace)'

      - task: AzureRmWebAppDeployment@4
        displayName: 'Deploy Azure App Service'
        retryCountOnTaskFailure: 10
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'aug-dev-connection'
          appType: 'webApp'
          WebAppName: 'file-loader-back'
          packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
          WebConfigParameters: '-Handler iisnode -NodeStartFile index.js -appType node'
          AppSettings: '-WEBSITE_NODE_DEFAULT_VERSION ~16'
