trigger:
  paths:
    include:
    - client_web_app/*
    exclude:
    - azure_infra/*
    - server_web_app/*
  branches:
    include:
    - master

variables:
  path: 'client_web_app'
  buildPath: 'client_web_app/build'

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: 'Build Artifact'
    jobs:
    - job: 'init'
      displayName: 'Initialize Project'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          cd $(path)
          npm install
          cd ..
        displayName: 'npm install'

      - script: |
          cd $(path)
          npm run build
          popd
          cd ..
        displayName: 'npm run build'

    - job: 'build'
      displayName: 'Build Artifact'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      steps:

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(buildPath)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop_client_dev'
          publishLocation: 'pipeline'

  - stage: deploy
    displayName: 'Deploy to Dev'
    jobs:
    - job: 'deploy'
      displayName: 'Deploy to Dev'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop_client_dev'
          targetPath: '$(Pipeline.Workspace)'

      - task: AzureRmWebAppDeployment@4
        displayName: 'Deploy Azure App Service'
        retryCountOnTaskFailure: 10
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'aug-dev-connection'
          appType: 'webApp'
          WebAppName: 'fileloaderapp'
          packageForLinux: '$(Pipeline.Workspace)/**/*.zip'