trigger:
  paths:
    include:
    - azure_infra/module/*
    - azure_infra/main.bicep
    - azure_infra/main.parameters.json
    exclude:
    - azure_infra/keyvault/*
   
  branches:
    include:
    - master

variables:
  serverName: 'fileloaderappserdev'
  kv: 'teamaz-key-vaultDev'
  frontEndAppName: 'fileloaderappDev'
  backEndAppName: 'file-loader-backDev'
  functionAppName: 'blobdownloaderDev'
  appConfigName: 'fileUploaderProAppConfigDev'
  appConfigConnSt: 'Endpoint=https://fileuploaderproappconfig.azconfig.io;Id=IonS-l9-s0:xFGH/OY4WWfwvja+MgZ5;Secret=L5Yp46TMvmWql/zmCZzrAZ3Z/ZGf4KJ5x8T8n2z34jQ='

pool:
  vmImage: windows-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy main bicep file'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'beselamConnection'
          subscriptionId: '6b13e739-7ee2-437c-b6f2-7e58e5cfc457'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'rg-beselam-aug-we'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: 'azure_infra/main.bicep'
          overrideParameters: '-serverName $(serverName) -kv $(kv) -frontEndAppName $(frontEndAppName) -backEndAppName $(backEndAppName) -functionAppName $(functionAppName) -appConfigName $(appConfigName) -appConfigConnSt $(appConfigConnSt)'
          csmParametersFile: 'azure_infra/main.parameters.json'
          deploymentMode: 'Incremental'
