trigger:
  paths:
    include:
    - azure_infra/module/*
    - azure_infra/main.bicep
    - azure_infra/main.parameters.json
    exclude:
    - azure_infra/keyvault/*
   
  branches:
    include:
    - production
    exclude:
    - master

variables:
  serverName: 'fileloaderappserpro'
  kv: 'teamaz-key-vaultPro'
  frontEndAppName: 'fileloaderappPro'
  backEndAppName: 'file-loader-backPro'
  functionAppName: 'blobdownloaderPro'
  appConfigName: 'fileUploaderProAppConfigPro'
  appConfigKeyValue: [ { key:'REACT_APP_API_URL', value:'https://fileloaderappbackend.azurewebsites.net' } , { key:'REACT_APP_API_URL_DEV' ,value:'http://localhost:3001' }, { key:'REACT_APP_REDERICT_URI' , value:'https://fileloaderappfrontend.azurewebsites.net' }, { key:'REACT_APP_REDERICT_URI_DEV', value:'http://localhost:3000' } ]


pool:
  vmImage: windows-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy main bicep file'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'productionConnection'
          subscriptionId: '6b13e739-7ee2-437c-b6f2-7e58e5cfc457'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'rg-team-1-aug-prod-we'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: 'azure_infra/main.bicep'
          csmParametersFile: 'azure_infra/main.parameters.json'
          overrideParameters: '-serverName $(serverName) -kv $(kv) -frontEndAppName $(frontEndAppName) -backEndAppName $(backEndAppName) -functionAppName $(functionAppName) -appConfigName $(appConfigName) -appConfigKeyValue $(appConfigKeyValue)'
          deploymentMode: 'Incremental'
